#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# This is a test procedure. It analyses the weighted samplings of tau decay
# vertices, generated by `run-sampling.py`.

import json
import math
from retro.event import EventIterator
from retro import TAU_BR_MU

def load(path):
    """Load samples
    """
    weight, weight2, generated = 0., 0., 0
    for event in EventIterator(path):
        w, n = event["statistics"]
        weight += w
        weight2 += w**2
        generated += n
    weight /= generated
    weight2 /= generated
    sigma = ((weight2 - weight**2) / generated)**0.5
    return weight, sigma

if __name__ == "__main__":
    c0, c1 = map(lambda x: math.cos(math.pi / 180. * x), (90.0, 92.5))
    I0 = (10**10.5 - 10**7.5) * (600E+03**2 * 3E+03) * (
          (c0 - c1) * 2. * math.pi) * (1. - TAU_BR_MU)
    I1, _ = load("share/events-E.json")
    I2, _ = load("share/events-E2.json")
    print I1 / I0, I2 / I0
